### ISSUE TITLE
SQL Error when running `ActiveMedian.create_function`

### ISSUE THREAD

**Issue by Skowt** [ankane/active_median#5]
When running the command `ActiveMedian.create_function` I get the following error:

```
ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FUNCTION median(anyarray)
```

Using mysql2 gem. Anything I should be doing beforehand?

**Comment by ankane** [comment]
Hi Daniel, ActiveMedian only works with PostgreSQL unfortunately.

**Comment by Skowt** [comment]
Got it thanks @ankane 👍  Missed that on the README. Thanks for the answer!

**Comment by ankane** [comment]
@stevebissett From my understanding, MySQL only supports aggregate UDFs in C and C++, not SQL. https://dba.stackexchange.com/questions/17267/how-do-i-create-a-user-defined-aggregate-function
