### ISSUE TITLE
PG::UndefinedFunction: ERROR:  function median(numeric) does not exist

### ISSUE THREAD

**Issue by danielwestendorf** [ankane/active_median#6]
Wanted to share something I ran into.

Ran into a problem with the function not existing on subsequent runs of my CI and/or after a `rails db:reset` call. This is because the create function isn't stored in the schema.rb.

You can switch to `:sql` as your schema structure, or you can make sure to run:

`bundle exec rails runner "ActiveMedian.create_function"` every time you reset your database. 

Make sure to run `RAILS_ENV=test bundle exec rails runner "ActiveMedian.create_function"` too if you need it for a test database (like CI).

**Comment by danielwestendorf** [comment]
Alternatively, I've manually created a rake task which hooks into `db:setup`

```ruby
namespace :db do
  task create_median_function: :environment do
    ActiveMedian.create_function
  end

  task :setup => :create_median_function
end
```

**Comment by ankane** [comment]
Hey @danielwestendorf, great solution 👍 I added it to the readme.
